# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Scrumptious' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SDWebImage'

  # Pods for Scrumptious

  target 'ScrumptiousTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScrumptiousUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
